### Get User (Token expires after 60s)
GET  http://34.101.78.157:5000/users
Authorization: Bearer <token>



### Register User
POST http://34.101.78.157:5000/register
Content-Type: application/json

{
    "name": "tesnama1",
    "email": "tesemail1234@gmail.com",
    "password": "1234567",
    "rePassword": "1234567"
}

POST http://34.101.78.157:5000/login
Content-Type: application/json

{
    "email": "tesemail1234@gmail.com",
    "password": "1234567"
}

### Get New Token
GET http://34.101.78.157:5000/token
Content-Type: application/json

###
SERVER : 34.101.78.157
PORT : 5000

